language: android
jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools

    # The BuildTools version used by your project
    - build-tools-23.0.1
    - extra-google-gcm
    - extra-google-google_play_services
    - extra-google-google_play_services_froyo
    - extra-google-m2repository
    - extra-google-play_apk_expansion
    - extra-google-play_billing
    - extra-google-play_licensing

    # The SDK version used to compile your project
    - android-21
    - android-23

env:
  - GRADLE_HOME=gradle-2.12/bin

before_script:
  - sudo add-apt-repository ppa:cwchien/gradle -y
  - sudo apt-get update -y
  - sudo apt-get install gradle -y
  - sudo gradle -version

script:
  - cd calculator && sudo gradle build
  - cd .. && cd Call && sudo gradle build
  - cd .. && cd MyLoggerApp && sudo gradle build

