language: android
jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-21

env:
  - GRADLE_HOME=gradle-2.12/bin

before_script:
  - sudo wget https://services.gradle.org/distributions/gradle-2.12-all.zip
  - sudo unzip gradle-2.12-all.zip
  - sudo gradle -version
script:
  - cd calculator && sudo gradle build
